xset -b
xset -r rate 250 30
xset m default
xset s 3600 3600

setxkbmap -option 'ctrl:nocaps'
xbindkeys --poll-rc

xsetroot -cursor_name left_ptr
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
xrandr --dpi 230
feh --bg-fill ~/Downloads/wallpaper.png

exec i3